# Generated by Django 5.2.14 on 2026-05-10 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/guards/')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('guard_tag', models.CharField(default='Gate Guard', max_length=50)),
                ('digital_id', models.CharField(max_length=50, unique=True)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='ids/guards/')),
                ('gate_registered_on', models.CharField(blank=True, max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('gates_assigned_to', models.ManyToManyField(blank=True, related_name='assigned_guards', to='cameras.gatewithcamera')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guards_registered', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
