# Generated by Django 5.2.14 on 2026-05-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GateWithCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_name', models.CharField(max_length=100)),
                ('camera_name', models.CharField(max_length=100)),
                ('gate_camera_id', models.CharField(max_length=50, unique=True)),
                ('power', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('OFFLINE', 'Offline')], default='ACTIVE', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('installation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gate with Camera',
                'verbose_name_plural': 'Gates with Cameras',
            },
        ),
    ]
