# Generated by Django 5.2.14 on 2026-05-10 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/visitors/')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_first_entry', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('visitor_tag', models.CharField(default='Guest', max_length=50)),
                ('digital_id', models.CharField(max_length=50, unique=True)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='ids/visitors/')),
                ('gate_registered_on', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('seen_by_guard', models.BooleanField(default=False)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to='guards.guardprofile')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='visitors.visitor')),
            ],
        ),
    ]
