# Generated by Django 5.2.14 on 2026-05-10 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/staff/')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('position', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('staff_tag', models.CharField(default='Staff Member', max_length=50)),
                ('digital_id', models.CharField(max_length=50, unique=True)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='ids/staff/')),
                ('gate_registered_on', models.CharField(blank=True, max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
