# Generated by Django 5.2.14 on 2026-05-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/admins/')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('admin_tag', models.CharField(default='System Admin', max_length=50)),
                ('digital_id', models.CharField(max_length=50, unique=True)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='ids/admins/')),
                ('gate_registered_on', models.CharField(blank=True, max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('gates_assigned_to', models.ManyToManyField(blank=True, related_name='assigned_admins', to='cameras.gatewithcamera')),
            ],
        ),
    ]
