# Generated by Django 5.2.14 on 2026-05-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('face_front', models.ImageField(upload_to='biometrics/faces/')),
                ('face_left', models.ImageField(upload_to='biometrics/faces/')),
                ('face_right', models.ImageField(upload_to='biometrics/faces/')),
                ('face_down', models.ImageField(upload_to='biometrics/faces/')),
                ('face_unusual', models.ImageField(upload_to='biometrics/faces/')),
                ('id_card_front', models.ImageField(upload_to='biometrics/ids/')),
                ('id_card_back', models.ImageField(upload_to='biometrics/ids/')),
                ('face_encodings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Biometric Data',
            },
        ),
    ]
